package com.example.gymworkout.ui.screens.nutrition

import androidx.compose.animation.AnimatedVisibility
import androidx.compose.animation.fadeIn
import androidx.compose.animation.slideInVertically
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.itemsIndexed
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.AutoAwesome
import androidx.compose.material.icons.filled.CheckCircle
import androidx.compose.material.icons.filled.Edit
import androidx.compose.material.icons.filled.FitnessCenter
import androidx.compose.material.icons.filled.Psychology
import androidx.compose.material.icons.filled.Restaurant
import androidx.compose.material3.Button
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Checkbox
import androidx.compose.material3.CheckboxDefaults
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.FilledTonalButton
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.material3.TopAppBar
import androidx.compose.material3.TopAppBarDefaults
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateListOf
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.platform.LocalFocusManager
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.ui.text.input.KeyboardCapitalization
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.example.gymworkout.ai.AiObjectiveGenerator
import com.example.gymworkout.data.NutritionTarget
import kotlinx.coroutines.delay

data class ObjectiveSelection(
    val objective: AiObjectiveGenerator.GeneratedObjective,
    var selected: Boolean = true,
    var editedTarget: Float = objective.target,
    var editedName: String = objective.name,
    var editedUnit: String = objective.unit,
    var alreadyExists: Boolean = false
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun AiObjectiveDialog(
    existingTargets: List<NutritionTarget> = emptyList(),
    onDismiss: () -> Unit,
    onAddObjectives: (List<ObjectiveSelection>) -> Unit
) {
    var inputText by remember { mutableStateOf("") }
    var hasGenerated by remember { mutableStateOf(false) }
    var isProcessing by remember { mutableStateOf(false) }
    val generatedObjectives = remember { mutableStateListOf<ObjectiveSelection>() }
    val focusManager = LocalFocusManager.current

    if (isProcessing) {
        LaunchedEffect(Unit) {
            delay(600)
            val results = AiObjectiveGenerator.generateObjectives(inputText)
            // Build sets of existing target identifiers for quick lookup
            val existingBuiltInCategories = existingTargets
                .filter { !it.isCustom }
                .map { it.category.uppercase() }
                .toSet()
            val existingCustomLabels = existingTargets
                .filter { it.isCustom }
                .map { it.label.lowercase().trim() }
                .toSet()

            generatedObjectives.clear()
            generatedObjectives.addAll(results.map { obj ->
                val exists = if (obj.isBuiltIn && obj.builtInCategory != null) {
                    obj.builtInCategory.name in existingBuiltInCategories
                } else {
                    obj.name.lowercase().trim() in existingCustomLabels
                }
                ObjectiveSelection(
                    objective = obj,
                    selected = !exists,
                    alreadyExists = exists
                )
            })
            hasGenerated = true
            isProcessing = false
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Icon(
                            Icons.Default.AutoAwesome,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(24.dp)
                        )
                        Spacer(modifier = Modifier.width(8.dp))
                        Column {
                            Text(
                                "AI Objective Generator",
                                style = MaterialTheme.typography.titleMedium,
                                fontWeight = FontWeight.Bold
                            )
                            Text(
                                "Describe your goals in plain text",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                },
                navigationIcon = {
                    IconButton(onClick = onDismiss) {
                        Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = "Back")
                    }
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = MaterialTheme.colorScheme.surface
                )
            )
        }
    ) { padding ->
        LazyColumn(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
                .padding(horizontal = 16.dp),
            verticalArrangement = Arrangement.spacedBy(12.dp)
        ) {
            // Info card
            item {
                Spacer(modifier = Modifier.height(4.dp))
                Card(
                    shape = RoundedCornerShape(16.dp),
                    colors = CardDefaults.cardColors(
                        containerColor = MaterialTheme.colorScheme.primaryContainer.copy(alpha = 0.3f)
                    )
                ) {
                    Row(
                        modifier = Modifier.padding(16.dp),
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Icon(
                            Icons.Default.Psychology,
                            contentDescription = null,
                            tint = MaterialTheme.colorScheme.primary,
                            modifier = Modifier.size(32.dp)
                        )
                        Spacer(modifier = Modifier.width(12.dp))
                        Column {
                            Text(
                                "On-Device AI",
                                style = MaterialTheme.typography.labelLarge,
                                fontWeight = FontWeight.SemiBold,
                                color = MaterialTheme.colorScheme.primary
                            )
                            Text(
                                "Runs 100% offline. Describe your nutrition & habit goals and objectives will be created automatically.",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                }
            }

            // Text input
            item {
                OutlinedTextField(
                    value = inputText,
                    onValueChange = {
                        inputText = it
                        if (hasGenerated) {
                            hasGenerated = false
                            generatedObjectives.clear()
                        }
                    },
                    label = { Text("Describe your goals") },
                    placeholder = { Text("e.g. I want to drink 3L water, eat 150g protein, meditate 15 min daily...") },
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(160.dp),
                    keyboardOptions = KeyboardOptions(
                        capitalization = KeyboardCapitalization.Sentences,
                        imeAction = ImeAction.Done
                    ),
                    keyboardActions = KeyboardActions(
                        onDone = { focusManager.clearFocus() }
                    ),
                    colors = OutlinedTextFieldDefaults.colors(
                        focusedBorderColor = MaterialTheme.colorScheme.primary,
                        unfocusedBorderColor = MaterialTheme.colorScheme.outlineVariant
                    ),
                    shape = RoundedCornerShape(12.dp)
                )
            }

            // Example prompts (hidden after generation)
            if (!hasGenerated) {
                item {
                    Text(
                        "Try an example:",
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
                item {
                    Column(verticalArrangement = Arrangement.spacedBy(6.dp)) {
                        AiObjectiveGenerator.examplePrompts.take(4).forEach { example ->
                            Card(
                                modifier = Modifier
                                    .fillMaxWidth()
                                    .clickable {
                                        inputText = example
                                        hasGenerated = false
                                        generatedObjectives.clear()
                                    },
                                shape = RoundedCornerShape(10.dp),
                                colors = CardDefaults.cardColors(
                                    containerColor = MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.5f)
                                )
                            ) {
                                Text(
                                    text = example,
                                    style = MaterialTheme.typography.bodySmall,
                                    fontStyle = FontStyle.Italic,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                                    maxLines = 2,
                                    overflow = TextOverflow.Ellipsis,
                                    modifier = Modifier.padding(horizontal = 12.dp, vertical = 8.dp)
                                )
                            }
                        }
                    }
                }
            }

            // Generate button
            item {
                FilledTonalButton(
                    onClick = {
                        if (inputText.isNotBlank()) {
                            focusManager.clearFocus()
                            isProcessing = true
                            generatedObjectives.clear()
                        }
                    },
                    enabled = inputText.isNotBlank() && !isProcessing,
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    if (isProcessing) {
                        CircularProgressIndicator(
                            modifier = Modifier.size(18.dp),
                            strokeWidth = 2.dp,
                            color = MaterialTheme.colorScheme.onSecondaryContainer
                        )
                    } else {
                        Icon(Icons.Default.AutoAwesome, contentDescription = null, modifier = Modifier.size(18.dp))
                    }
                    Spacer(modifier = Modifier.width(8.dp))
                    Text(if (isProcessing) "Analyzing..." else if (hasGenerated) "Re-analyze" else "Generate Objectives")
                }
            }

            // Results inline below
            if (hasGenerated && generatedObjectives.isNotEmpty()) {
                // Header
                item {
                    Row(
                        modifier = Modifier.fillMaxWidth(),
                        horizontalArrangement = Arrangement.SpaceBetween,
                        verticalAlignment = Alignment.CenterVertically
                    ) {
                        Text(
                            "${generatedObjectives.size} objectives found",
                            style = MaterialTheme.typography.titleSmall,
                            fontWeight = FontWeight.SemiBold
                        )
                        TextButton(onClick = {
                            val selectableItems = generatedObjectives.filter { !it.alreadyExists }
                            val allSelected = selectableItems.all { it.selected }
                            generatedObjectives.forEachIndexed { i, item ->
                                if (!item.alreadyExists) {
                                    generatedObjectives[i] = item.copy(selected = !allSelected)
                                }
                            }
                        }) {
                            Text(if (generatedObjectives.filter { !it.alreadyExists }.all { it.selected }) "Deselect All" else "Select All")
                        }
                    }
                }

                // Nutrition section
                val nutritionItems = generatedObjectives.filter { it.objective.isNutritionRelated }
                if (nutritionItems.isNotEmpty()) {
                    item {
                        SectionHeader(
                            icon = Icons.Default.Restaurant,
                            title = "Nutrition",
                            count = nutritionItems.size,
                            color = Color(0xFFFF8A65)
                        )
                    }
                    itemsIndexed(
                        nutritionItems,
                        key = { _, item -> "n_${item.objective.name}" }
                    ) { _, item ->
                        val globalIndex = generatedObjectives.indexOf(item)
                        AnimatedVisibility(
                            visible = true,
                            enter = fadeIn() + slideInVertically { it / 2 }
                        ) {
                            ObjectiveCard(
                                item = item,
                                onToggle = {
                                    generatedObjectives[globalIndex] = item.copy(selected = !item.selected)
                                },
                                onTargetChange = { newTarget ->
                                    generatedObjectives[globalIndex] = item.copy(editedTarget = newTarget)
                                },
                                onNameChange = { newName ->
                                    generatedObjectives[globalIndex] = item.copy(editedName = newName)
                                },
                                onUnitChange = { newUnit ->
                                    generatedObjectives[globalIndex] = item.copy(editedUnit = newUnit)
                                }
                            )
                        }
                    }
                }

                // Habits section
                val habitItems = generatedObjectives.filter { !it.objective.isNutritionRelated }
                if (habitItems.isNotEmpty()) {
                    item {
                        Spacer(modifier = Modifier.height(2.dp))
                        SectionHeader(
                            icon = Icons.Default.FitnessCenter,
                            title = "Habits",
                            count = habitItems.size,
                            color = Color(0xFFAB47BC)
                        )
                    }
                    itemsIndexed(
                        habitItems,
                        key = { _, item -> "h_${item.objective.name}" }
                    ) { _, item ->
                        val globalIndex = generatedObjectives.indexOf(item)
                        AnimatedVisibility(
                            visible = true,
                            enter = fadeIn() + slideInVertically { it / 2 }
                        ) {
                            ObjectiveCard(
                                item = item,
                                onToggle = {
                                    generatedObjectives[globalIndex] = item.copy(selected = !item.selected)
                                },
                                onTargetChange = { newTarget ->
                                    generatedObjectives[globalIndex] = item.copy(editedTarget = newTarget)
                                },
                                onNameChange = { newName ->
                                    generatedObjectives[globalIndex] = item.copy(editedName = newName)
                                },
                                onUnitChange = { newUnit ->
                                    generatedObjectives[globalIndex] = item.copy(editedUnit = newUnit)
                                }
                            )
                        }
                    }
                }

                // Confirm button
                item {
                    Spacer(modifier = Modifier.height(4.dp))
                    val selectedCount = generatedObjectives.count { it.selected && !it.alreadyExists }
                    Button(
                        onClick = {
                            onAddObjectives(generatedObjectives.filter { it.selected && !it.alreadyExists })
                        },
                        enabled = selectedCount > 0,
                        modifier = Modifier
                            .fillMaxWidth()
                            .height(50.dp),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Icon(Icons.Default.CheckCircle, contentDescription = null, modifier = Modifier.size(20.dp))
                        Spacer(modifier = Modifier.width(8.dp))
                        Text(
                            "Add $selectedCount Objective${if (selectedCount != 1) "s" else ""}",
                            style = MaterialTheme.typography.titleSmall,
                            fontWeight = FontWeight.SemiBold
                        )
                    }
                    Spacer(modifier = Modifier.height(16.dp))
                }
            }

            // No results
            if (hasGenerated && generatedObjectives.isEmpty()) {
                item {
                    Card(
                        shape = RoundedCornerShape(12.dp),
                        colors = CardDefaults.cardColors(
                            containerColor = MaterialTheme.colorScheme.errorContainer.copy(alpha = 0.3f)
                        )
                    ) {
                        Column(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(20.dp),
                            horizontalAlignment = Alignment.CenterHorizontally
                        ) {
                            Text(
                                "No objectives found",
                                style = MaterialTheme.typography.titleSmall,
                                fontWeight = FontWeight.SemiBold
                            )
                            Spacer(modifier = Modifier.height(4.dp))
                            Text(
                                "Try being more specific. Mention nutrients (protein, calories, water), habits (meditation, steps), or supplements (creatine, omega-3).",
                                style = MaterialTheme.typography.bodySmall,
                                color = MaterialTheme.colorScheme.onSurfaceVariant
                            )
                        }
                    }
                }
            }
        }
    }
}

@Composable
private fun SectionHeader(
    icon: ImageVector,
    title: String,
    count: Int,
    color: Color
) {
    Row(
        verticalAlignment = Alignment.CenterVertically,
        modifier = Modifier.padding(vertical = 4.dp)
    ) {
        Box(
            modifier = Modifier
                .size(28.dp)
                .clip(CircleShape)
                .background(color.copy(alpha = 0.15f)),
            contentAlignment = Alignment.Center
        ) {
            Icon(icon, contentDescription = null, tint = color, modifier = Modifier.size(16.dp))
        }
        Spacer(modifier = Modifier.width(8.dp))
        Text(
            "$title ($count)",
            style = MaterialTheme.typography.labelLarge,
            fontWeight = FontWeight.SemiBold,
            color = MaterialTheme.colorScheme.onSurface
        )
    }
}

@Composable
private fun ObjectiveCard(
    item: ObjectiveSelection,
    onToggle: () -> Unit,
    onTargetChange: (Float) -> Unit,
    onNameChange: (String) -> Unit,
    onUnitChange: (String) -> Unit
) {
    val obj = item.objective
    var isEditingTarget by remember { mutableStateOf(false) }
    var isEditingName by remember { mutableStateOf(false) }
    var editText by remember(item.editedTarget) {
        mutableStateOf(
            item.editedTarget.let {
                if (it == it.toLong().toFloat()) it.toLong().toString() else it.toString()
            }
        )
    }
    var editUnitText by remember(item.editedUnit) { mutableStateOf(item.editedUnit) }
    var editNameText by remember(item.editedName) { mutableStateOf(item.editedName) }
    val focusManager = LocalFocusManager.current

    val alreadyExists = item.alreadyExists
    val contentAlpha = if (alreadyExists) 0.5f else 1f

    Card(
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(
            containerColor = if (alreadyExists)
                MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.2f)
            else if (item.selected)
                MaterialTheme.colorScheme.secondaryContainer.copy(alpha = 0.4f)
            else
                MaterialTheme.colorScheme.surfaceVariant.copy(alpha = 0.3f)
        ),
        modifier = Modifier.fillMaxWidth()
    ) {
        Row(
            modifier = Modifier
                .fillMaxWidth()
                .then(if (!alreadyExists) Modifier.clickable { onToggle() } else Modifier)
                .padding(horizontal = 12.dp, vertical = 10.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Checkbox(
                checked = item.selected,
                onCheckedChange = if (!alreadyExists) { { onToggle() } } else null,
                enabled = !alreadyExists,
                colors = CheckboxDefaults.colors(
                    checkedColor = MaterialTheme.colorScheme.primary,
                    uncheckedColor = MaterialTheme.colorScheme.outline,
                    disabledCheckedColor = MaterialTheme.colorScheme.outline.copy(alpha = 0.4f),
                    disabledUncheckedColor = MaterialTheme.colorScheme.outline.copy(alpha = 0.4f)
                )
            )

            Column(modifier = Modifier.weight(1f)) {
                if (isEditingName && !alreadyExists) {
                    OutlinedTextField(
                        value = editNameText,
                        onValueChange = { editNameText = it },
                        modifier = Modifier.fillMaxWidth(),
                        keyboardOptions = KeyboardOptions(
                            capitalization = KeyboardCapitalization.Words,
                            imeAction = ImeAction.Done
                        ),
                        keyboardActions = KeyboardActions(
                            onDone = {
                                val trimmed = editNameText.trim()
                                if (trimmed.isNotBlank()) onNameChange(trimmed)
                                isEditingName = false
                                focusManager.clearFocus()
                            }
                        ),
                        minLines = 1,
                        maxLines = 3,
                        textStyle = MaterialTheme.typography.bodyLarge.copy(fontWeight = FontWeight.Medium),
                        shape = RoundedCornerShape(8.dp)
                    )
                } else {
                    Row(verticalAlignment = Alignment.CenterVertically) {
                        Text(
                            text = item.editedName,
                            style = MaterialTheme.typography.bodyLarge,
                            fontWeight = FontWeight.Medium,
                            color = MaterialTheme.colorScheme.onSurface.copy(alpha = contentAlpha),
                            modifier = Modifier
                                .weight(1f, fill = false)
                                .then(if (!alreadyExists) Modifier.clickable { isEditingName = true } else Modifier)
                        )
                        if (!alreadyExists) {
                            IconButton(
                                onClick = { isEditingName = true },
                                modifier = Modifier.size(24.dp)
                            ) {
                                Icon(
                                    Icons.Default.Edit,
                                    contentDescription = "Edit name",
                                    modifier = Modifier.size(14.dp),
                                    tint = MaterialTheme.colorScheme.onSurfaceVariant
                                )
                            }
                        }
                    }
                }
                Row(
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.spacedBy(6.dp)
                ) {
                    Text(
                        text = if (obj.isBuiltIn) "Built-in tracker" else "Custom objective",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = contentAlpha)
                    )
                    if (alreadyExists) {
                        Text(
                            text = "Already added",
                            style = MaterialTheme.typography.labelSmall,
                            fontWeight = FontWeight.SemiBold,
                            color = MaterialTheme.colorScheme.tertiary,
                            modifier = Modifier
                                .background(
                                    MaterialTheme.colorScheme.tertiaryContainer.copy(alpha = 0.5f),
                                    RoundedCornerShape(4.dp)
                                )
                                .padding(horizontal = 6.dp, vertical = 2.dp)
                        )
                    }
                }
            }

            if (isEditingTarget && !alreadyExists) {
                OutlinedTextField(
                    value = editText,
                    onValueChange = { editText = it },
                    modifier = Modifier.width(72.dp),
                    keyboardOptions = KeyboardOptions(
                        keyboardType = KeyboardType.Decimal,
                        imeAction = ImeAction.Done
                    ),
                    keyboardActions = KeyboardActions(
                        onDone = {
                            editText.toFloatOrNull()?.let { onTargetChange(it) }
                            val trimmedUnit = editUnitText.trim()
                            if (trimmedUnit.isNotBlank() && trimmedUnit != obj.unit) onUnitChange(trimmedUnit)
                            isEditingTarget = false
                            focusManager.clearFocus()
                        }
                    ),
                    singleLine = true,
                    textStyle = MaterialTheme.typography.bodyMedium
                )
                Spacer(modifier = Modifier.width(4.dp))
                if (!obj.isBuiltIn) {
                    OutlinedTextField(
                        value = editUnitText,
                        onValueChange = { editUnitText = it },
                        modifier = Modifier.width(56.dp),
                        keyboardOptions = KeyboardOptions(imeAction = ImeAction.Done),
                        keyboardActions = KeyboardActions(
                            onDone = {
                                editText.toFloatOrNull()?.let { onTargetChange(it) }
                                val trimmedUnit = editUnitText.trim()
                                if (trimmedUnit.isNotBlank()) onUnitChange(trimmedUnit)
                                isEditingTarget = false
                                focusManager.clearFocus()
                            }
                        ),
                        singleLine = true,
                        textStyle = MaterialTheme.typography.bodySmall
                    )
                } else {
                    Text(item.editedUnit, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            } else {
                Text(
                    text = formatTarget(item.editedTarget),
                    style = MaterialTheme.typography.titleMedium,
                    fontWeight = FontWeight.Bold,
                    color = MaterialTheme.colorScheme.primary.copy(alpha = contentAlpha)
                )
                Spacer(modifier = Modifier.width(4.dp))
                Text(item.editedUnit, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant.copy(alpha = contentAlpha))
                if (!alreadyExists) {
                    Spacer(modifier = Modifier.width(4.dp))
                    IconButton(onClick = { isEditingTarget = true }, modifier = Modifier.size(28.dp)) {
                        Icon(Icons.Default.Edit, contentDescription = "Edit target", modifier = Modifier.size(16.dp), tint = MaterialTheme.colorScheme.onSurfaceVariant)
                    }
                }
            }
        }
    }
}

private fun formatTarget(value: Float): String {
    return if (value == value.toLong().toFloat()) {
        value.toLong().toString()
    } else {
        String.format("%.1f", value)
    }
}
